### ISSUE TITLE
Test issue creation

### ISSUE THREAD

**Issue by cmclean3** [cmclean3/Masters-Project#3]
Have wrapped a few of the files into a project and pushed to a new github repository. I'll delete the old one.

I think i have worked out how to use Github with Rstudio and Github desktop - the only unclear part is whether i should be working on a branch on my own computer or the master. I understand the logic of working on the branch and then pushing/pulling - the only unclear part is why when i have tried this Rstuido saves any changes to the file in the same desktop folder (and over the master) that is synced with github (rather than created its own branch file). Does this make sense?

I'm still working on the replication portion of the code - i've added the Tbills and cleaned up a few files. I've also started looking for SA data - we won't have much data for the TOP40 total return (only from 2002/2003) and might struggle to create a total return index for SA gov bonds (seems to be periods where there wasn't a bond in the data). I'll continue looking at this tomorrow night. 

Will keep you updated with my progress.

Test picture upload below...

![img_2420](https://cloud.githubusercontent.com/assets/16827877/22185183/94204eae-e0e9-11e6-8147-6dfd3c74a670.JPG)

cheers

**Comment by csrvermaak** [comment]
@cmclean3 - good job :) 

To be honest, I don't use branches with GitHuub.... It adds a layer of complexity, and I haven't yet had the need to use it. I just work in master.... Hope that helps? I will explain the way I understand branches next time we meet, it is a bit lengthy to type out :).

Perhaps try a bond fund instead of the Index?

**Comment by csrvermaak** [comment]
@cmclean3 -nice usage of the Projects as well
