### ISSUE TITLE
Mutate referencing values in same column but row above

### ISSUE THREAD

**Issue by cmclean3** [cmclean3/Masters-Project#4]
Hi @csrvermaak 

I'm trying to code a mutate the signal column for some timing strategies that need to refer to previous signal, i.e. the row above for the same signal column.

For example with a standard simple moving average strategy with columns price and SMA, my mutate to calculate signal would be:
`"signal"  = lag(ifelse(Price<SMA,0,1)),`

I'm now trying to do create a band strategy that says if Price < SMA then be flat (signal =0), else if previous signal was long, stay long (signal = 1), else if price > 1.05% * SMA then enter long (signal =1), else 0. I've tried variations of:

`"signal"  = lag(ifelse(Price<SMA,0,ifelse(lag(signal)=1,1,ifelse(price>1.05%*SMA,1,0))))`

Searched online for a solution but had no luck - do you know if something like this is possible with mutate?

thanks

**Comment by csrvermaak** [comment]
Hi @cmclean3 

I would try to first mutate a new column, called eg PrevSignal = lag(signal,1), to get the "lagged" signal as a seperate column on the same row (also, as a sanity check!)

Then use that in a normal mutate.

Let me know if that helps? Lag is definitely the right function, you just need to get the syntax right, and by breaking the problem up into smaller chunks, the "bug" might be easier to find.

Also - debugging is ALWAYS a nightmare at 23:30 on a Sunday evening! :) The solution will be much clearer this morning.

Let me know?

**Comment by cmclean3** [comment]
thanks - sorted with a simple loop and if statement.

doc is updated to include the new strategy now
